### PR TITLE
Fixed styles

### PR DESCRIPTION
**Pull request by ar4s**

### CODE REVIEW

**Comment by ar4s** [comment]
centered checkboxes
f45c96

**Comment by ar4s** [comment]
bulk edit
63b62436_3

change form
63b62436_2

change list
63b62436_1

**Comment by ar4s** [comment]
a57e080

**Comment by ar4s** [comment]
c512ae40

**Comment by szok** [comment]
:ok:

**Comment by mkurek** [comment]
:ok:

**Pull request merged**
