### PR TITLE
Add cloud images support

### PR DESCRIPTION
**Pull request by tomez**

### CODE REVIEW

**Comment by mkurek** [comment]
Are you going to use this image in any other model?

**Review by romcheg — CHANGES_REQUESTED** [review]
Could you please generate migrations? Another point is that CloudImage should not be a base object because base objects are accountable per service environment.

**Comment by tomez** [comment]
@mkurek not this time, in future PRs

**Review by mkurek — APPROVED** [review]

**Review by romcheg — APPROVED** [review]
My concerns have been resolved. LGTM, thanks!

**Pull request merged**
