### PR TITLE
[WIP] Ralph 3 in Django 1.9

### PR DESCRIPTION
**Pull request by szok**
- [x]  travis only django 1.9
- [x]  Django 1.9
- [x] pip django 1.9

### CODE REVIEW

**Comment by mkurek** [comment]
blocked by https://github.com/django-extensions/django-extensions/pull/791

**Comment by mkurek** [comment]
django-extensions PR is already merged. @szok - could you make this PR mergable?

**Comment by vi4m** [comment]
We should merge it _after_ releasing ralph 3.0, and doing some proper testing (manual for example)

**Comment by mkurek** [comment]
http://www.nooooooooooooooo.com/ :stuck_out_tongue_winking_eye:

**Pull request closed without merging**
