### PR TITLE
Added Czech localization

### PR DESCRIPTION
**Pull request by p-bo**

### CODE REVIEW

**Comment by vi4m** [comment]
Thanks! 👍

**Review by vi4m — APPROVED** [review]

**Comment by romcheg** [comment]
@p-bo Thank you for the contribution. We'd like to merge more languages to Ralph. There is one small issue that is none of us speaks Czech so we cannot make a review here :)

Could you please ask a few colleagues of yours who are familiar with the domain and also are native Czech speakers to review the translation and comment on this PR?

**Comment by p-bo** [comment]
@romcheg I do understand your concerns, but I'm mere volunteer, so there are no colleagues to ask for review. But if it helps, I'm translating lot of other projects too – in the same domain are: 
https://github.com/glpi-project/glpi/blob/master/locales/cs_CZ.po
https://github.com/glpi-project/doc-install/tree/master/source/locale/cs_CZ/LC_MESSAGES
https://github.com/OCSInventory-NG/OCSInventory-ocsreports/blob/master/plugins/language/cs_CZ/cs_CZ.txt
https://github.com/Opmantek/open-audit/blob/master/code_igniter/application/views/lang/cs.inc
https://github.com/fusioninventory/fusioninventory-for-glpi/blob/master/locales/cs_CZ.po
+ all maintained GLPI plugins

as well for example:
FreeNAS
XigmaNAS (previously NAS4Free)
OpenMediavault
FreedomBox
LXQt
Lumina desktop
Mint Linux
OPNsense
Zentyal
…and many others.

**Comment by romcheg** [comment]
@p-bo I poked a few friends of mine from RedHat -- they have a big office in Brno so maybe they can find someone who can review the translation. The thing that concerns me is not whether or not you have skills -- on the contrary, I can see you've done great translations in other projects. I'm more concerned about some typos and other small nasty things that sometimes happen and then only someone else can notice that.

Say you what, I'm going to run Ralph with this patch and switch it to Czech to verify nothing breaks in general. Then I will merge it. If the people I mentioned will find some time to review the translation, we will create a separate PR for that and will mention you there.

**Comment by p-bo** [comment]
I see and thanks for trust and constructive mindset – will then look at result on http://ralph-demo.allegro.tech/ and will proofread too :)

**Comment by romcheg** [comment]
@p-bo thank you for the translation. Seems to work fine for me. I will let you know when it's deployed to ralph-demo.

**Pull request merged**
