### PR TITLE
[Reopened] Functionality allows inject custom tracking code

### PR DESCRIPTION
**Pull request by quamilek**
Allows tracking code from providers such as: Google Analytics, Piwik etc.

Reopened PR: https://github.com/allegro/ralph/pull/1251

### CODE REVIEW

**Comment by xor-xor** [comment]
What's changed..?

**Comment by quamilek** [comment]
@xor-xor comment https://github.com/allegro/ralph/pull/1264/files#diff-0f7870dfd795a7930b03ee5ffcecf679R379

**Comment by xor-xor** [comment]
:ok:

**Comment by vi4m** [comment]
LGTM

**Pull request merged**
