### PR TITLE
feat: contribute helm chart

### PR DESCRIPTION
**Pull request by stxm**
2nd interation of helm chart based on [docker-compose.yml](https://github.com/allegro/ralph/blob/ng/docker/docker-compose.yml)

### CODE REVIEW

**Comment by stxm** [comment]
@vi4m @ar4s  Could you have a look at this pr?

**Comment by vi4m** [comment]
@romcheg what do you think about the second iteration?

**Comment by romcheg** [comment]
@vi4m dude, I'm thinking about getting my family to safety right now, not about helm charts. I did some re-work of the original chart including some tests but I have much more important things to take care of at the moment.

**Comment by vi4m** [comment]
I'm sorry, I've notified you by mistake. I hope your family is safe; let me know if you need anything.

**Comment by stxm** [comment]
Hope all of you are doing well and good. @vi4m Is there any progress with the review ?

**Pull request closed without merging**
