### PR TITLE
Configuration path (a.k.a venture)

### PR DESCRIPTION
**Pull request by mkurek**
- models for configuration path (a.k.a. venture/role in Ralph2)
- with API and importer (ex. from Ralph2)

### CODE REVIEW

**Comment by vi4m** [comment]
@andrzej-jankowski what about ansible ? could we reuse module, class in this case?

**Comment by mkurek** [comment]
@vi4m i've described briefly in docs how this could be used for ansible but someone with better ansible-skill should look at it.

**Comment by szok** [comment]
:ok:

**Comment by ar4s** [comment]
:ok:

**Pull request merged**
