### PR TITLE
Use python-3.5 in the debian package

### PR DESCRIPTION
**Pull request by romcheg**

### CODE REVIEW

**Comment by mkurek** [comment]
What about users of older ubuntu/debians which don't include python-3.5 in their packages?

**Comment by romcheg** [comment]
@mkurek should we recommend them to update to the latest stable/lts version of their distributions? There is another patch that changes the version of python from 3.4 to 3.5 in the test environment, so shipping a deb package on the older version of python that works a bit differently could lead to certain problems.

**Review by mkurek — APPROVED** [review]

**Comment by mkurek** [comment]
remember about the docs :)

**Comment by vi4m** [comment]
@romcheg docs please

**Pull request closed without merging**
