### PR TITLE
Fixed exporting asset type and status

### PR DESCRIPTION
**Pull request by mkurek**
In Ralph NG, there is separated asset status for BO and DC (introduced in #1815). This PR fixes export of BO and DC asset statuses to be compatible with NG.

### CODE REVIEW

**Comment by szok** [comment]
:ok:

**Comment by vi4m** [comment]
Your commit message: `This PR fix export` -> `This PR fixes export`

**Comment by mkurek** [comment]
@vi4m done

**Comment by vi4m** [comment]
It should be done with separate package called ralph-interop with DI. Instead, we did just a bastard child of two systems, mixing them, and breaking Classes Encapsulation rules . This horrible practice should be punished, and this pull request should not be merged. But...

Fuck it. New world is coming, let's spend our energy on Ralph-NG instead! :)

**Comment by vi4m** [comment]
LLCBDSOTOT
Looks Like Crap But Don't Spend Our Time On It

**Pull request merged**
