### PR TITLE
Remove Network foreign key from IPAddress model 

### PR DESCRIPTION
**Pull request by szok**
Remove Network foreign key from IPAddress model

### CODE REVIEW

**Comment by ar4s** [comment]
:ok:

**Comment by mkurek** [comment]
:ok:

**Comment by mkurek** [comment]
add unit test for that

**Comment by mkurek** [comment]
http://www.nooooooooooooooo.com/ 

Don't run reset.sh - create 0002 migration with removing network field - we'll squash all migrations into one file someday. 

Btw could you clean-up network tab in data-center asset? 
- [ ] Ip should be added (new ip) or selected from list of existing ip addresses (or at least saving with existing ip should not raise an error - it should assign asset to this ip). 
- [ ] There could be only one management address
- [ ] Cannot add new rows (jquery error)

**Comment by ar4s** [comment]
_Cannot add new rows (jquery error)_ - @szok you can omit this bug (unless you know how fix this) - I will take care of it in next week.

**Comment by szok** [comment]
@mkurek

**Pull request closed without merging**
