### PR TITLE
Added ``get_absolute_url`` to RackAccessory

### PR DESCRIPTION
**Pull request by ar4s**
This change fixed bad link in accessory.

Connected to #1614

### CODE REVIEW

**Comment by mkurek** [comment]
1) why are you removing `src/ralph/dc_view/static/partials/rack/rack_view.html`?

2) could you fix https://github.com/allegro/ralph/issues/1614#issuecomment-121567771 in this PR too?

**Comment by ar4s** [comment]
1) This file is replaced by `src/ralph/dc_view/static/partials/data_center/data_center.detail.rack.html`
2) I forget :smile:

**Comment by mkurek** [comment]
:ok:

**Comment by ghost** [comment]
:ok:

**Pull request merged**
