### PR TITLE
Better login box

### PR DESCRIPTION
**Pull request by ar4s**
- removed top bar
- added bar to fieldset
- normalized padding and margin between fields, labels and button
  spectacle tj6446
  instead of
  spectacle 2

### CODE REVIEW

**Comment by mkurek** [comment]
gr8! :ok:

**Comment by szok** [comment]
:ok:

**Comment by vi4m** [comment]
awesome!

**Comment by ar4s** [comment]
spectacle m14548

**Comment by szok** [comment]
:+1:

**Pull request merged**
