### PR TITLE
[WIP] Java Script test exit code

### PR DESCRIPTION
**Pull request by szok**
Disabled JS tests in travis.

### CODE REVIEW

**Comment by mkurek** [comment]
why we are disabling it in travis?

**Comment by szok** [comment]
Because with Arek we have decided for turned off.

**Comment by vi4m** [comment]
@ar4s any info why ?

**Comment by vi4m** [comment]
Explanation should be included in a commit message as well.

**Comment by mkurek** [comment]
@vi4m i've added WIP prefix; this PR needs some improvements - instead of turning JS units tests off someone should make it finally working. @xliiv @szok @ar4s challenge accepted? :sunglasses: :beers:

**Pull request closed without merging**
