### PR TITLE
Give raw-id widget some style + choices widget is 100% length.

### PR DESCRIPTION
**Pull request by ghost**
Raw-id field:
    - search icon was moved to line where input is
    - human value got close to input
Choices widget:
    - 100% length to input

Special thanks to @ar4s for improvements to this change :D

### CODE REVIEW

**Comment by xliiv** [comment]
Widget with value:
raw-id-with-value

Widget without value:
raw-id-without-value

**Comment by ghost** [comment]
raw-id-widget

**Comment by mkurek** [comment]
:ok:

**Comment by ar4s** [comment]
:ok:

**Pull request merged**
