### PR TITLE
Allow primary key fields to be accessed in read-only mode.

### PR DESCRIPTION
**Pull request by msuszko**
This adds view permission to primary key fields.

### CODE REVIEW

**Comment by mkurek** [comment]
@msuszko what is your motivation for this? what is the possible use case of readonly id?

**Comment by msuszko** [comment]
I'd like to present id field on admin list (.list_display). It works unless PermissionAdminMixin is used or user is an admin.
This patch allows to grant _view permission, and view id field for non-admin users.

**Comment by msuszko** [comment]
Motivations is the id field doesn't change and can be used as additional reference (as serial number, barcode, inventory number). I'm developing buisiness application registry on top of Ralph 3 and it has primary key used as application identifier

**Comment by mkurek** [comment]
so it's :ok: for me, but please squash it into one commit

**Comment by msuszko** [comment]
done.

**Comment by vi4m** [comment]
LGTM

**Comment by ar4s** [comment]
:ok:

**Pull request merged**
