### PR TITLE
Multiadd / duplicate improvements

### PR DESCRIPTION
**Pull request by mkurek**
- fixed delimiting by pipe (|)
- added rack in dc asset description table
- improved saved message - now shows items count and links to added objects
- added ability to make field non-required
- using 'one_of_mulitvalue_required' in MultiAddView
- added 'niw' field to DC Asset multiadd

Connected to #1809

### CODE REVIEW

**Comment by szok** [comment]
:ok:

**Comment by vi4m** [comment]
What about the "position" field ? Is it sill required? Should be optional IMHO.

**Comment by mkurek** [comment]
Yes it is - it's required both in Ralph 2.0 (assets) and NG, just like Rack field.

**Comment by vi4m** [comment]
Why?

**Comment by mkurek** [comment]
As discussed, leave position field right now as it is - we can always change it to not being required.

**Comment by ar4s** [comment]
:ok:

**Pull request merged**
