### PR TITLE
Fix #3032 by removing sqlparse from requirements

### LINKED ISSUE #3032: Some problem when making installation.
Enviroment :
ralph-ng (2017-04-22 13:05:51)
ubuntu 14.04.05
python2.7 python3.4
mysql-server5.5
redies-server2.8.4

builtins.TypeError
TypeError: process() takes 2 positional arguments but 3 were given
Traceback (most recent call last)
File "/usr/local/lib/python3.4/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
return self.application(environ, start_response)
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
response = self.get_response(request)
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 233, in get_response
response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
return debug.technical_500_response(request, *exc_info)
File "/usr/local/lib/python3.4/dist-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
six.reraise(exc_type, exc_value, tb)
File "/usr/local/lib/python3.4/dist-packages/six.py", line 686, in reraise
raise value
File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 223, in get_response
response = middleware_method(request, response)
File "/usr/local/lib/python3.4/dist-packages/debug_toolbar/middleware.py", line 129, in process_response
panel.generate_stats(request, response)
File "/usr/local/lib/python3.4/dist-packages/debug_toolbar/panels/sql/panel.py", line 192, in generate_stats
query['sql'] = reformat_sql(query['sql'])
File "/usr/local/lib/python3.4/dist-packages/debug_toolbar/panels/sql/utils.py", line 27, in reformat_sql
return swap_fields(''.join(stack.run(sql)))
File "/usr/local/lib/python3.4/dist-packages/sqlparse/engine/__init__.py", line 44, in run
stream = filter_.process(self, stream)
TypeError: process() takes 2 positional arguments but 3 were given

127.0.0.1 - - [22/Apr/2017 06:50:28] "GET /login/?next=/ HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/django/contrib/staticfiles/handlers.py", line 63, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/wsgi.py", line 189, in __call__
    response = self.get_response(request)
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 233, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 261, in handle_uncaught_exception
    return debug.technical_500_response(request, *exc_info)
  File "/usr/local/lib/python3.4/dist-packages/django_extensions/management/technical_response.py", line 6, in null_technical_500_response
    six.reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.4/dist-packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.4/dist-packages/django/core/handlers/base.py", line 223, in get_response
    response = middleware_method(request, response)
  File "/usr/local/lib/python3.4/dist-packages/debug_toolbar/middleware.py", line 129, in process_response
    panel.generate_stats(request, response)
  File "/usr/local/lib/python3.4/dist-packages/debug_toolbar/panels/sql/panel.py", line 192, in generate_stats
    query['sql'] = reformat_sql(query['sql'])
  File "/usr/local/lib/python3.4/dist-packages/debug_toolbar/panels/sql/utils.py", line 27, in reformat_sql
    return swap_fields(''.join(stack.run(sql)))
  File "/usr/local/lib/python3.4/dist-packages/sqlparse/engine/__init__.py", line 44, in run
    stream = filter_.process(self, stream)
TypeError: process() takes 2 positional arguments but 3 were given

### PR DESCRIPTION
**Pull request by rcsheets**
I don't really understand the problem, but this seems to fix it.

### CODE REVIEW

**Comment by ar4s** [comment]
``sqlparse`` are used by ``django-debug-toolbar`` and ``django-silk`` on development mode in Ralph. If think you can remove this package from ``base.txt``.

**Comment by rcsheets** [comment]
Removing `sqlparse` from `requirements/base.txt` and then doing `pip uninstall sqlparse` followed by `pip install -r requirements.txt` results in an `ImportError: No module named 'sqlparse'` when I next run `make run`.

**Comment by rcsheets** [comment]
Hmm, but in a clean python3.5 virtualenv, if I do `pip install django-debug-toolbar` I end up with:

    Successfully installed Django-2.0.2 django-debug-toolbar-1.9.1 pytz-2018.3 sqlparse-0.2.4

So I'm not sure what I'm doing wrong that's keeping `sqlparse` from getting installed in my ralph virtualenv.

**Comment by rcsheets** [comment]
Oh, I just didn't actually specify `-r requirements/dev.txt`, so `pip` didn't get any of the dev requirements. I think you're right that it can be removed, but I'm just double checking now. If it works without specifying `sqlparse`, I'll amend this PR.

**Review by ar4s — APPROVED** [review]

**Pull request merged**
