### PR TITLE
Hiding liquidated status in BO and DC Asset

### PR DESCRIPTION
**Pull request by szok**
screen shot 2015-12-18 at 13 04 41

### CODE REVIEW

**Comment by mkurek** [comment]
Couldn't you extend filter for status field?

**Comment by szok** [comment]
But then by default we will not display objects with this status.

**Comment by mkurek** [comment]
And that's how your code is working too. IMO this should work as follows:
- by default all assets except liquidated are displayed (when `All` status filter is chosen or without status filter)
- liquidated assets are shown only when `liquidated` filter value is chosen

**Comment by mkurek** [comment]
:ok:

**Comment by ar4s** [comment]
:ok:

**Pull request merged**
