### PR TITLE
RAS-1327|Add start_usage in licences model

### PR DESCRIPTION
**Pull request by smaciejs**

### CODE REVIEW

**Comment by vi4m** [comment]
Documentation is missing?

**Review by vi4m — CHANGES_REQUESTED** [review]
Update documentation

**Review by szymi- — APPROVED** [review]

**Review by Blejwi — APPROVED** [review]

**Comment by smaciejs** [comment]
> Update documentation

@vi4m https://github.com/allegro/ralph/pull/3418

**Comment by romcheg** [comment]
@vi4m there is a separate PR for the documentation, could you please unblock this one?

**Review by vi4m — APPROVED** [review]

**Pull request merged**
