### PR TITLE
Add index to object_id in to custom fields

### PR DESCRIPTION
**Pull request by ar4s**
Custom field values inline in details view of asset generate query with where
statement which contains object_id. Now is more efficient -- ~1ms vs ~20ms in environment.

### CODE REVIEW

**Comment by mkurek** [comment]
Isn't only one commit in this PR appropriate?

**Comment by ar4s** [comment]
@mkurek my mistake

**Comment by mkurek** [comment]
:ok:

**Comment by szok** [comment]
:ok:

**Pull request merged**
