### PR TITLE
Add Support models to ng export

### PR DESCRIPTION
**Pull request by szok**
Added Support Model Resource for export.

### CODE REVIEW

**Comment by vi4m** [comment]
Where's the description?

**Comment by vi4m** [comment]
When you stick to the git log with headline and details, travis will fill it out correctly

for example:

zrzut ekranu 2015-07-03 o 13 52 45

**Comment by mkurek** [comment]
it's WIP

**Comment by ar4s** [comment]
:ok:

**Comment by mkurek** [comment]
:ok:

**Pull request merged**
