### PR TITLE
Better representation for CIs in `Jira Changes` (CMDB)

### PR DESCRIPTION
**Pull request by ghost**
Put CIs into div so that CSS overflow works and limited height to 300px.

### CODE REVIEW

**Comment by ar4s** [comment]
:ok:

**Comment by mkurek** [comment]
:ok:

**Comment by vi4m** [comment]
thank you @xliiv

**Comment by ghost** [comment]
No problem :)
That long list is only enclosed within a fixed-width div now, but in future we could changed it to something more relevant.

**Pull request merged**
