### PR TITLE
Added new commands ({dev, test}_ralph)

### PR DESCRIPTION
**Pull request by ar4s**
This is some shortcut. `ralph_dev` - run ralph with develop settings (`ralph.settings.dev`).
Now you can type for example `ralph_dev runserver_plus` instead of `ralph
runserver_plus --settings=ralph.settings.dev`

### CODE REVIEW

**Comment by mkurek** [comment]
"discussable" :smirk:

We're going to use vagrant for development so maybe we could add to some `.bashrc` file etc some environment variables settings:

```
export DJANGO_SETTINGS_MODULE="ralph.settings.dev"
```

**Comment by ar4s** [comment]
ok, but.. what if you want to run server in dev mode outside vagrant env (e.g. staging or prod :joy: )? IMHO it's small change and we know explicit (by `_dev` postfix) which settings is set.

**Comment by mkurek** [comment]
I know - but this will make it inconvenient to autocomplete ralph command (ex. `ral<tab>`) if there will be more than one command with `ralph` prefix (normally, if there is only one command autocompletion fill it and insert space at the end). So maybe `dev_ralph` instead of `ralph_dev` (this won't confuse not-dev users as well - probably normal users will not notice this command, but will notice `ralph_dev` command)?

**Comment by mkurek** [comment]
:ok:

**Pull request merged**
