### PR TITLE
Change 'f5app' strings to '.f5.' for discovering f5 devices.

### PR DESCRIPTION
**Pull request by jjagodzinski**

### CODE REVIEW

**Comment by jjagodzinski** [comment]
F5 has changed kernel name syntax. Earlier there was '.f5app' in kernel name, right now there is only .f5. Change is needed to discover new f5.

**Comment by mkurek** [comment]
Could we check for both (`.f5app` and `.f5.`) to keep backward compatibility with F5s with old kernel?

**Comment by jjagodzinski** [comment]
Ok, changed.

**Comment by mkurek** [comment]
ok - so please squash it into one commit and it's :ok: for me

**Comment by andrzej-jankowski** [comment]
:ok:

**Pull request merged**
